### ISSUE TITLE
form_builder_extra_fields from git is forbidden

### ISSUE THREAD

**Issue by divan** [danvick/flutter_form_builder#1070]
Hi, I'm trying to use the master branch of the `flutter_form_builder` while also using `form_builder_extra_fields` package.

Straightforward switch to git produces some versions incomatibilities.

pubspec.yaml
```
  flutter_form_builder: #^7.3.1
    git:
      url: git@github.com:danvick/flutter_form_builder.git
      path: packages/flutter_form_builder
```

`flutter pub get` error trying to add `flutter_builder_extra_fields`:

```
Because form_builder_extra_fields >=7.0.0-alpha.4 <7.0.0-alpha.5 depends on flutter_form_builder ^7.0.0-alpha.2 and form_builder_extra_fields <7.0.0-alpha.4 depends on flutter_form_builder ^7.0.0-alpha.1, form_builder_extra_fields <7.0.0-alpha.5 requires flutter_form_builder ^7.0.0-alpha.1.
And because form_builder_extra_fields >=7.0.0-alpha.5 <7.0.0-alpha.6 depends on flutter_form_builder ^7.0.0-alpha.3 and form_builder_extra_fields >=7.0.0-alpha.6 <7.0.0 depends on flutter_form_builder ^7.0.0-beta.0, form_builder_extra_fields <=7.0.0-alpha.6 requires flutter_form_builder ^7.0.0-alpha.1.
And because form_builder_extra_fields ^7.0.0 depends on flutter_form_builder ^7.0.0 and form_builder_extra_fields >=8.0.0 depends on flutter_form_builder ^7.1.1, every version of form_builder_extra_fields requires flutter_form_builder from hosted.
So, because adminui depends on both flutter_form_builder from git and form_builder_extra_fields any, version solving failed.
```

So, next I've added git spec for `flutter_builder_extra_fields` too. Now pubspec.yaml looks like:

```yaml
  flutter_form_builder: #^7.3.1
    git:
      url: git@github.com:danvick/flutter_form_builder.git
      path: packages/flutter_form_builder
  form_builder_extra_fields: 
    git:
      url: git@github.com:danvick/flutter_form_builder.git
      path: packages/form_builder_extra_fields
```

and the error is:

```
Because every version of form_builder_extra_fields from git depends on flutter_form_builder from hosted and <project> depends on flutter_form_builder from git, form_builder_extra_fields from git is forbidden.
So, because <project> depends on form_builder_extra_fields from git, version solving failed.
Running "flutter pub get" in adminui...
```

So the question is – how to use latest master branch of `flutter_form_builder` with one of its satellite packages?

**Comment by deandreamatias** [comment]
@divan Try use https://github.com/danvick/flutter_form_builder.git instead git@
git@is for ssh

**Comment by divan** [comment]
@deandreamatias thanks for the quick reply.

I don't think switching to git https changes anything (dependencies still refer to hosted packages)..

pubspec.yaml
```yaml
  flutter_form_builder: #^7.3.1
    git:
      url: https://github.com/danvick/flutter_form_builder.git
      path: packages/flutter_form_builder
  form_builder_extra_fields:
    git:
      url: https://github.com/danvick/flutter_form_builder.git
      path: packages/form_builder_extra_fields
  form_builder_validators:
    git:
      url: https://github.com/danvick/flutter_form_builder.git
      path: packages/form_builder_validators
```

An error:
```
flutter pub get
Because every version of form_builder_extra_fields from git depends on flutter_form_builder from hosted and <project> depends on flutter_form_builder from git, form_builder_extra_fields from git is forbidden.
So, because <project> depends on form_builder_extra_fields from git, version solving failed.
Running "flutter pub get" in <project>...
pub get failed (1; So, because <project> depends on form_builder_extra_fields from git, version solving failed.)
```
