### ISSUE TITLE
Update dependency packages - intl

### ISSUE THREAD

**Issue by shashikantshaale** [danvick/flutter_form_builder#187]
https://pub.dev/packages/intl 

```
Because every version of flutter_driver from sdk depends on intl 0.16.0 and every version of flutter_form_builder from git depends on intl ^0.15.8, flutter_driver from sdk is incompatible with flutter_form_builder from git.

So, because shaale depends on both flutter_form_builder from git and flutter_driver any from sdk, version solving failed.
pub get failed (1)
```

**Comment by shashikantshaale** [comment]
https://github.com/danvick/flutter_form_builder/issues/185#issuecomment-562030309 Helped

**Comment by danvick** [comment]
`intl` has been reverted to v0.15.8 in v3.7.0.
Alternatively you can fix this with depency overrides. Like so:
```
dependencies:
  ...
  flutter_form_builder: 3.6.1

dependency_overrides:
  intl: 0.15.8
```
