### ISSUE TITLE
Error: Type 'RangeSemanticFormatterCallback' not found.

### ISSUE THREAD

**Issue by carlomigueldy** [danvick/flutter_form_builder#382]
The package is not usable, I am getting this error

```
class DatePickerTheme with DiagnosticableMixin {
                           ^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.3.8/lib/src/datetime_picker_theme.dart:6:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class DatePickerTheme with DiagnosticableMixin {
      ^
../../.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.8.3/lib/src/chips_input.dart:88:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
 - TextInputClient.currentAutofillScope
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ChipsInputState<T> extends State<ChipsInput<T>>
      ^^^^^^^^^^^^^^^
../../development/flutter/packages/flutter/lib/src/services/text_input.dart:801:21: Context: 'TextInputClient.currentAutofillScope' is defined here.
  AutofillScope get currentAutofillScope;
                    ^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-4.0.0-alpha.8/lib/src/fields/form_builder_range_slider.dart:15:9: Error: 'RangeSemanticFormatterCallback' isn't a type.
  final RangeSemanticFormatterCallback semanticFormatterCallback;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by FetFrumos** [comment]
I have same error

**Comment by FetFrumos** [comment]
I fixed it. check the flutter version. i had a problem with beta channel.  When i switched to stable(1.17.5) - everything worked

**Comment by carlomigueldy** [comment]
> I fixed it. check the flutter version. i had a problem with beta channel. When i switched to stable(1.17.5) - everything worked

Oh alright, I will give it a try! 

I am using master channel by the way, probably that's why I was receiving this error

**Comment by carlomigueldy** [comment]
The stable channel does not work for me since there are properties that I use that are not avaiable in stable channel that were available in master channel

**Comment by a7mdragab** [comment]
I have the same problem now 
Master channel latest version
```
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_builder-3.12.0/lib/src/fields/form_builder_range_slider.dart:21:9: Error: 'RangeSemanticFormatterCallback' isn't a type.
  final RangeSemanticFormatterCallback semanticFormatterCallback;
```

Any suggestions?

**Comment by m-j-g** [comment]
yeah, same here.

**Comment by carlomigueldy** [comment]
I hope the author would see this issue so it gets fixed

**Comment by akshatshah** [comment]
I have the same problem

**Comment by liudonghua123** [comment]
I have the same problem. I now use master branch of flutter.

**Comment by liudonghua123** [comment]
I made some fix, see https://github.com/danvick/flutter_form_builder/pull/395 for more details.

Before the pr was merged, you can use the following dependences.

```yaml
dependency_overrides:
  flutter_form_builder: 
    git:
      url: git://github.com/liudonghua123/flutter_form_builder.git
      ref: fix_semanticFormatterCallback
```

**Comment by danvick** [comment]
Thanks, @liudonghua123 for your solution.

We cannot obviously merge the PR to the stable (master) branch of our package because it will cause breakage for those on other channels.

We will, therefore, include merge the PR into a new branch and release it as a pre-release version of the package.

**Comment by liudonghua123** [comment]
@danvick Yes, you are right, there are a lot of break api changes between `master` and `stable` channel of flutter. The best way to support different channel of flutter is publish multi tagged version.

**Comment by danvick** [comment]
For those with this issue consider using v3.14.0-alpha.*

```yaml
dependency_overrides:
  flutter_form_builder: v3.14.0-alpha.1
```

**Comment by maddog666** [comment]
When I add 

```
dependencies:
  flutter_form_builder: v3.14.0-alpha.1
```

I got 

```
Error on line 50, column 25 of pubspec.yaml: Invalid version constraint: Could not parse version "v3.14.0-alpha.1". Unknown text at "v3.14.0-alpha.1".
   ╷                                                                    
50 │   flutter_form_builder: v3.14.0-alpha.1                            
   │                         ^^^^^^^^^^^^^^^                            
   ╵      
```

**Comment by maddog666** [comment]
Using

``` 
  flutter_form_builder:
    git:
      url: git://github.com/liudonghua123/flutter_form_builder.git
      ref: fix_semanticFormatterCallback
```

I got 
```
../../../../.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.9.1/lib/src/chips_input.dart:88:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
 - TextInputClient.performPrivateCommand
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ChipsInputState<T> extends State<ChipsInput<T>>
      ^^^^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/services/text_input.dart:806:8: Context: 'TextInputClient.performPrivateCommand' is defined here.
  void performPrivateCommand(String action, Map<String, dynamic> data);
       ^^^^^^^^^^^^^^^^^^^^^
```

Below is my Flutter doctor -v result
```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.93, on Mac OS X 10.15.6 19G73, locale en-AU)
    • Flutter version 1.21.0-10.0.pre.93 at /Users/williamhu/Documents/Develop/flutter
    • Framework revision bee9522f18 (2 hours ago), 2020-08-13 22:53:27 -0400
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/williamhu/Documents/Develop/adt-bundle/sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/williamhu/Documents/Develop/adt-bundle/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPad Air (3rd generation) (mobile) • 4C4A2243-C819-4532-84C7-F5C919677BE1 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

! Doctor found issues in 1 category.
```

**Comment by liudonghua123** [comment]
@maddog666 Hi, maybe the `master` channel of flutter changed some api.

**Comment by maddog666** [comment]
@liudonghua123 Yeah. It broke all the dependencies. I changed to the `stable`, then it broke `build_runner` because it's running `Dart 2.9.1`, if I temporary removed build_runner, I still get

```
../../../../.pub-cache/git/flutter_form_builder-../../../../.pub-cache/git/flutter_form_builder-3f972c779702d8488582663980626058010f023b/lib/src/fields/form_builder_range_slider.dart:117:53: Error: The argument type 'String Function(double)' can't be assigned to the parameter type 'String Function(RangeValues)'.
 - 'RangeValues' is from 'package:flutter/src/material/slider_theme.dart' ('../../flutter/packages/flutter/lib/src/material/slider_theme.dart').
                  semanticFormatterCallback: widget.semanticFormatterCallback,
                                                    ^
```

**Comment by danvick** [comment]
> When I add
> 
> ```
> dependencies:
>   flutter_form_builder: v3.14.0-alpha.1
> ```
> 
> I got
> 
> ```
> Error on line 50, column 25 of pubspec.yaml: Invalid version constraint: Could not parse version "v3.14.0-alpha.1". Unknown text at "v3.14.0-alpha.1".
>    ╷                                                                    
> 50 │   flutter_form_builder: v3.14.0-alpha.1                            
>    │                         ^^^^^^^^^^^^^^^                            
>    ╵      
> ```

I had a typo there, drop the "v". Should be:
```yaml
dependencies:
  flutter_form_builder: ^3.14.0-alpha.1
```

**Comment by Windol** [comment]
I tested the proposed solution on pull request # 422 through the following configuration:
```yaml
dependencies:
  flutter_form_builder:
    git:
      url: git://github.com/ryanhz/flutter_form_builder.git
      ref: master
```
It's working perfectly for me.

**Comment by Windol** [comment]
> > When I add
> > ```
> > dependencies:
> >   flutter_form_builder: v3.14.0-alpha.1
> > ```
> > 
> > 
> > I got
> > ```
> > Error on line 50, column 25 of pubspec.yaml: Invalid version constraint: Could not parse version "v3.14.0-alpha.1". Unknown text at "v3.14.0-alpha.1".
> >    ╷                                                                    
> > 50 │   flutter_form_builder: v3.14.0-alpha.1                            
> >    │                         ^^^^^^^^^^^^^^^                            
> >    ╵      
> > ```
> 
> I had a typo there, drop the "v". Should be:
> 
> ```yaml
> dependencies:
>   flutter_form_builder: ^3.14.0-alpha.1
> ```

I have this error using 3.14.0-alpha.1:
```console
> flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Syncing files to device Chrome...
/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.9.1/lib/src/chips_input.dart:88:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
 - TextInputClient.performPrivateCommand
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ChipsInputState<T> extends State<ChipsInput<T>>
      ^^^^^^^^^^^^^^^
/C:/tools/flutter/packages/flutter/lib/src/services/text_input.dart:806:8: Context: 'TextInputClient.performPrivateCommand' is defined here.
  void performPrivateCommand(String action, Map<String, dynamic> data);
       ^^^^^^^^^^^^^^^^^^^^^
```
```console
> flutter doctor --verbose
[√] Flutter (Channel master, 1.21.0-10.0.pre.114, on Microsoft Windows [versÃ£o 10.0.18363.1016], locale pt-BR)
    • Flutter version 1.21.0-10.0.pre.114 at C:\tools\flutter
    • Framework revision b2c0970aa7 (4 days ago), 2020-08-16 06:11:02 -0400
    • Engine revision b300be3df3
    • Dart version 2.10.0 (build 2.10.0-34.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:/Android/android-sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:/Android/android-sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_231\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30406.217
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code, 64-bit edition (version 1.48.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (4 available)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [versÃ£o 10.0.18363.1016]
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 84.0.4147.135
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 81.0.416.86

! Doctor found issues in 1 category.
```

**Comment by slavap** [comment]
@danvick @Windol 
^3.14.0-alpha.1 works successfully for me, no problem with flutter_chips_input-1.9.1
And I have in pubspec.yaml flutter_chips_input as separate dependancy:
flutter_chips_input: ^1.9.1

**Comment by Windol** [comment]
@slavap this is my pubspec.yaml:
```yaml
name: generate_form
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  schema_form:
    path: ..
  schema_widget: ^1.0.0-5
  logging: ^0.11.4
  json_schema: ^2.2.1
  intl: ^0.16.1
  http: ^0.12.2
  provider: ^4.3.2+1
  flutter_form_builder: 3.14.0-alpha.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2

flutter:
  uses-material-design: true
```
And this is my pubspec.lock:
```yaml
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  _fe_analyzer_shared:
    dependency: transitive
    description:
      name: _fe_analyzer_shared
      url: "https://pub.dartlang.org"
    source: hosted
    version: "7.0.0"
  analyzer:
    dependency: transitive
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.39.17"
  archive:
    dependency: transitive
    description:
      name: archive
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.13"
  args:
    dependency: transitive
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.0"
  asn1lib:
    dependency: transitive
    description:
      name: asn1lib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.5"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.5.0-nullsafety"
  basic_utils:
    dependency: transitive
    description:
      name: basic_utils
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.6.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0-nullsafety"
  build:
    dependency: transitive
    description:
      name: build
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  build_config:
    dependency: transitive
    description:
      name: build_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.2"
  build_daemon:
    dependency: transitive
    description:
      name: build_daemon
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.4"
  build_resolvers:
    dependency: transitive
    description:
      name: build_resolvers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.11"
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.10.2"
  build_runner_core:
    dependency: transitive
    description:
      name: build_runner_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.0.1"
  built_collection:
    dependency: transitive
    description:
      name: built_collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.3.2"
  built_value:
    dependency: transitive
    description:
      name: built_value
      url: "https://pub.dartlang.org"
    source: hosted
    version: "7.1.0"
  characters:
    dependency: transitive
    description:
      name: characters
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0-nullsafety.2"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0-nullsafety"
  checked_yaml:
    dependency: transitive
    description:
      name: checked_yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  cli_repl:
    dependency: transitive
    description:
      name: cli_repl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0+1"
  cli_util:
    dependency: transitive
    description:
      name: cli_util
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  clock:
    dependency: transitive
    description:
      name: clock
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0-nullsafety"
  code_builder:
    dependency: transitive
    description:
      name: code_builder
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.4.1"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.15.0-nullsafety.2"
  colorize:
    dependency: transitive
    description:
      name: colorize
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  convert:
    dependency: transitive
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  country_pickers:
    dependency: transitive
    description:
      name: country_pickers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.4"
  csslib:
    dependency: transitive
    description:
      name: csslib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.16.1"
  dart2_constant:
    dependency: transitive
    description:
      name: dart2_constant
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2+dart2"
  dart_style:
    dependency: transitive
    description:
      name: dart_style
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.6"
  date_range_picker:
    dependency: transitive
    description:
      name: date_range_picker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.6"
  datetime_picker_formfield:
    dependency: transitive
    description:
      name: datetime_picker_formfield
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0-nullsafety"
  file:
    dependency: transitive
    description:
      name: file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.2.1"
  fixnum:
    dependency: transitive
    description:
      name: fixnum
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.11"
  fluri:
    dependency: transitive
    description:
      name: fluri
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.8"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_cache_manager:
    dependency: transitive
    description:
      name: flutter_cache_manager
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.1"
  flutter_chips_input:
    dependency: "direct main"
    description:
      name: flutter_chips_input
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.1"
  flutter_colorpicker:
    dependency: transitive
    description:
      name: flutter_colorpicker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.4"
  flutter_form_builder:
    dependency: "direct main"
    description:
      name: flutter_form_builder
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.14.0-alpha.1"
  flutter_keyboard_visibility:
    dependency: transitive
    description:
      name: flutter_keyboard_visibility
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.2.1"
  flutter_plugin_android_lifecycle:
    dependency: transitive
    description:
      name: flutter_plugin_android_lifecycle
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.8"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_touch_spin:
    dependency: transitive
    description:
      name: flutter_touch_spin
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  flutter_typeahead:
    dependency: transitive
    description:
      name: flutter_typeahead
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.7"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  get_it:
    dependency: transitive
    description:
      name: get_it
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.4"
  glob:
    dependency: transitive
    description:
      name: glob
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  graphs:
    dependency: transitive
    description:
      name: graphs
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  html:
    dependency: transitive
    description:
      name: html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.14.0+3"
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.2"
  http_multi_server:
    dependency: transitive
    description:
      name: http_multi_server
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.0"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.3"
  image:
    dependency: transitive
    description:
      name: image
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.12"
  image_picker:
    dependency: transitive
    description:
      name: image_picker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.7+4"
  image_picker_for_web:
    dependency: transitive
    description:
      name: image_picker_for_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0+1"
  image_picker_platform_interface:
    dependency: transitive
    description:
      name: image_picker_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  intl:
    dependency: "direct main"
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.16.1"
  io:
    dependency: transitive
    description:
      name: io
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.4"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.1+1"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.1"
  json_schema:
    dependency: "direct main"
    description:
      name: json_schema
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.1"
  logging:
    dependency: "direct main"
    description:
      name: logging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.4"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.10-nullsafety"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0-nullsafety.2"
  mime:
    dependency: transitive
    description:
      name: mime
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.6+3"
  nested:
    dependency: transitive
    description:
      name: nested
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.4"
  node_interop:
    dependency: transitive
    description:
      name: node_interop
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  node_io:
    dependency: transitive
    description:
      name: node_io
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1+2"
  package_config:
    dependency: transitive
    description:
      name: package_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.3"
  package_resolver:
    dependency: transitive
    description:
      name: package_resolver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.10"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.0-nullsafety"
  path_provider:
    dependency: transitive
    description:
      name: path_provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.11"
  path_provider_linux:
    dependency: transitive
    description:
      name: path_provider_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.1+2"
  path_provider_macos:
    dependency: transitive
    description:
      name: path_provider_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.4"
  path_provider_platform_interface:
    dependency: transitive
    description:
      name: path_provider_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  pedantic:
    dependency: transitive
    description:
      name: pedantic
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.0+1"
  petitparser:
    dependency: transitive
    description:
      name: petitparser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.0"
  phone_number:
    dependency: transitive
    description:
      name: phone_number
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.2+4"
  platform:
    dependency: transitive
    description:
      name: platform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.1"
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  pointycastle:
    dependency: transitive
    description:
      name: pointycastle
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  pool:
    dependency: transitive
    description:
      name: pool
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.0"
  process:
    dependency: transitive
    description:
      name: process
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.13"
  provider:
    dependency: "direct main"
    description:
      name: provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.3.2+1"
  pub_semver:
    dependency: transitive
    description:
      name: pub_semver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.4"
  pubspec_parse:
    dependency: transitive
    description:
      name: pubspec_parse
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.5"
  quiver:
    dependency: transitive
    description:
      name: quiver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.3"
  random_string:
    dependency: transitive
    description:
      name: random_string
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  rating_bar:
    dependency: transitive
    description:
      name: rating_bar
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  rxdart:
    dependency: transitive
    description:
      name: rxdart
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.24.1"
  sass:
    dependency: transitive
    description:
      name: sass
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.24.4"
  schema_form:
    dependency: "direct main"
    description:
      path: "C:/Users/windo/Documents/Flutter/schema_form"
      relative: false
    source: path
    version: "2.0.0-alpha+1"
  schema_widget:
    dependency: "direct main"
    description:
      name: schema_widget
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0-5"
  shelf:
    dependency: transitive
    description:
      name: shelf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.9"
  shelf_web_socket:
    dependency: transitive
    description:
      name: shelf_web_socket
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.3"
  signature:
    dependency: transitive
    description:
      name: signature
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.2.0"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  sockjs_client:
    dependency: transitive
    description:
      path: "."
      ref: "0.3.5"
      resolved-ref: "2e8dc8d2fe8486d31b6e220277c94d746ced1691"
      url: "git://github.com/Workiva/sockjs-dart-client.git"
    source: git
    version: "0.3.5"
  sockjs_client_wrapper:
    dependency: transitive
    description:
      name: sockjs_client_wrapper
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.14"
  source_gen:
    dependency: transitive
    description:
      name: source_gen
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.6"
  source_maps:
    dependency: transitive
    description:
      name: source_maps
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.8"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.0-nullsafety"
  sqflite:
    dependency: transitive
    description:
      name: sqflite
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.1"
  sqflite_common:
    dependency: transitive
    description:
      name: sqflite_common
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2+1"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.10.0-nullsafety"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0-nullsafety"
  stream_transform:
    dependency: transitive
    description:
      name: stream_transform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0-nullsafety"
  synchronized:
    dependency: transitive
    description:
      name: synchronized
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.0+2"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0-nullsafety"
  test_api:
    dependency: transitive
    description:
      name: test_api
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.19-nullsafety"
  timing:
    dependency: transitive
    description:
      name: timing
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.1+2"
  tuple:
    dependency: transitive
    description:
      name: tuple
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.0-nullsafety.2"
  uri:
    dependency: transitive
    description:
      name: uri
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.3+1"
  utf:
    dependency: transitive
    description:
      name: utf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.0+5"
  uuid:
    dependency: transitive
    description:
      name: uuid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.0"
  validators:
    dependency: transitive
    description:
      name: validators
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0-nullsafety.2"
  vin_decoder:
    dependency: transitive
    description:
      name: vin_decoder
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.2"
  w_common:
    dependency: transitive
    description:
      name: w_common
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.20.3"
  w_transport:
    dependency: transitive
    description:
      name: w_transport
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.2.8"
  watcher:
    dependency: transitive
    description:
      name: watcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.7+13"
  web_socket_channel:
    dependency: transitive
    description:
      name: web_socket_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  xdg_directories:
    dependency: transitive
    description:
      name: xdg_directories
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.0"
  xml:
    dependency: transitive
    description:
      name: xml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.6.1"
  yaml:
    dependency: transitive
    description:
      name: yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.1"
sdks:
  dart: ">=2.10.0-0.0.dev <2.10.0"
  flutter: ">=1.17.5 <2.0.0"
```
The final result is this:
```console
> flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.9.1/lib/src/chips_input.dart:88:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
 - TextInputClient.performPrivateCommand
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ChipsInputState<T> extends State<ChipsInput<T>>
      ^^^^^^^^^^^^^^^
/C:/tools/flutter/packages/flutter/lib/src/services/text_input.dart:806:8: Context: 'TextInputClient.performPrivateCommand' is defined here.
  void performPrivateCommand(String action, Map<String, dynamic> data);
       ^^^^^^^^^^^^^^^^^^^^^
Failed to compile application.
```
