### ISSUE TITLE
Cannot build with flutter_form_builder: ^4.0.2 as dependency

### ISSUE THREAD

**Issue by vladnicula** [danvick/flutter_form_builder#639]
Hey, I found this package via a review video on youtube. Seems quite an impressive package which could save me a lot of time. Unfortunately, it fails to build when I add it to my deps.

Adding `flutter_form_builder: ^4.0.2` to my dependencies in `pubspec.yaml` causes the project to fail the build with the following error:

```
../../.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.4.0/lib/flutter_datetime_picker.dart:215:48: Error: No named parameter with the name 'shadowThemeOnly'.
    ThemeData inheritTheme = Theme.of(context, shadowThemeOnly: true);
                                               ^^^^^^^^^^^^^^^
../../apps/flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^
```

My flutter `pubspec.yaml` is this:

```
name: fluttest
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

  # https://pub.dev/packages/google_fonts
  # see the link above for deploying the fonts to production and 
  # bundling them into native apps
  # also see https://medium.com/@rastogi_saurav/how-to-implement-your-design-system-in-flutter-from-scratch-8d94e2f423a1
  # which might be the basis of a design system
  google_fonts: ^1.1.1

  flutter_svg: ^0.19.2+1

  provider: ^4.3.2+2

  # working with firebase
  # see https://firebase.flutter.dev/docs/installation/web/
  # and https://firebase.flutter.dev/docs/installation/ios
  # and https://firebase.flutter.dev/docs/installation/android
  # for how to set this up properly on each system
  # 
  # also see: https://firebase.google.com/docs/flutter/setup
  # for a more detailed perspective on the firebase side of things
  firebase_core: "0.5.3"

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.18.3+1
  cloud_firestore: ^0.14.3+1
  firebase_storage: ^5.2.0

  # Mobx for state management. Will aim to use it as a flat global uber class if possible
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2

  # Simple time range selector 
  time_range_picker: ^1.1.1

  # Used my version until the maintainer patched a bug that I fixed
  # time_range_picker:
  #   git:
  #     url: git://github.com/vladnicula/flutter_time_range_picker.git
  #     ref: master

  # Magic charts! 
  fl_chart: ^0.12.0

  # Date formatiing and such. Used intiially to parse the month name 
  # of the date objects for the charts of mesruments.
  intl: ^0.16.1

  flutter_form_builder: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # required by the mobx code generationo system
  # run with flutter packages pub run build_runner build
  # watch with flutter packages pub run build_runner watch
  # run clean when having erros with flutter packages pub run build_runner watch --delete-conflicting-outputs
  # see more at: https://mobx.netlify.app/getting-started 
  build_runner: ^1.10.6
  mobx_codegen: ^1.1.2

  # Adds sentry
  sentry_flutter: ^4.0.0-beta.1

  # Loading indicator for submiting forms and doing locked in data changes
  # https://pub.dev/packages/loading_animations
  loading_animations: ^2.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
  - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

Running `flutter doctor -v` I get:
```
flutter doctor -v
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Linux, locale C.UTF-8)
    • Flutter version 1.24.0-10.2.pre at /home/vladnicula/apps/flutter
    • Framework revision 022b333a08 (3 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```

**Comment by vladnicula** [comment]
If I add `  flutter_form_builder: ^3.0.0` as a dependency which installs then following version (taken form the lock file)

```
  flutter_form_builder:
    dependency: "direct main"
    description:
      name: flutter_form_builder
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.14.1"
```

Things work fine. I am able to run version 3 of the package.
