### ISSUE TITLE
4.1.0 build fails - issue with CocoaPods

### ISSUE THREAD

**Issue by rbobko93** [danvick/flutter_form_builder#656]
Hey,

I was trying to use version 4.1.0 in my project. Adding package to pubspec and simply running `flutter pub get` throws an error.

```
[!] CocoaPods could not find compatible versions for pod "phone_number":
      In Podfile:
        phone_number (from `.symlinks/plugins/phone_number/ios`)

    Specs satisfying the `phone_number (from `.symlinks/plugins/phone_number/ios`)` dependency were found, but they required a higher minimum deployment target.
```

```
Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 11.
```

Tried `flutter clean` `pod install` and `pod upgrade` also updated my flutter version to latest stable one, but nothing helped. It seems like ios pod `PhoneNumberKit` is not getting installed, but I'm not sure if that's the cause of the issue. 

pod version 1.10.0
Flutter version 
```
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (13 days ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

Any help would be appreciated!

**Comment by rbobko93** [comment]
Since the problem is with `phone_number` package I have started new flutter project and tried installing it on there. Finished fine. Here is my projects pubspec file:
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  badges: 1.1.1
  cupertino_icons: 0.1.3
  flip_card: 0.4.4
  form_field_validator: 1.0.1
  google_fonts: 1.1.1
  google_maps_flutter: 0.5.28+1
  intl: 0.16.1
  maps_launcher: 1.2.2+1
  permission_handler: 5.0.1+1
  phone_number: 0.8.1
  quiver: 2.1.3
  url_launcher: 5.5.0
  uuid: 2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
```
