### ISSUE TITLE
Error: Method not found 'ButtonTheme.bar'

### ISSUE THREAD

**Issue by joechchung** [danvick/flutter_form_builder#698]
When trying to run flutter application in Android Studio (v4.1.0), receiving this error:
```
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/date_range_picker-1.0.6/lib/date_range_picker.dart:1152:44: Error: Method not found: 'ButtonTheme.bar'.
    final Widget actions = new ButtonTheme.bar(
                                           ^^^
```

Removing the `flutter_form_builder` plugin allows the app to run.

`flutter doctor -v`: 
```
[✓] Flutter (Channel dev, 1.26.0-17.1.pre, on Microsoft Windows [Version 10.0.19042.782], locale en-GB)
    • Flutter version 1.26.0-17.1.pre at C:\flutter
    • Framework revision c40e5294dd (2 days ago), 2021-01-29 08:44:18 -0800
    • Engine revision 5d3477eab4
    • Dart version 2.12.0 (build 2.12.0-259.0.dev)
```

Flutter SDK settings:
[Image](https://prnt.sc/xxg96x)

`pubspec.yaml`:
```
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: '^4.2.0'
  amplify_core: '<1.0.0'
  amplify_flutter: '<1.0.0'
  amplify_auth_cognito: '<1.0.0'
  amplify_analytics_pinpoint: '<1.0.0'
  intl: '^0.16.1'

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
```
