### ISSUE TITLE
date_range_picker is deprecated

### ISSUE THREAD

**Issue by LefebvreIlyas** [danvick/flutter_form_builder#701]
Hello everyone,

The readme of [`date_range_picker`](https://github.com/anicdh/date_range_picker) indicates that

```md
# [Deprecated] Date Range Picker

Currently Flutter has supported date range picker, so I think my mission is done. Thanks for using my lib.
Link: https://api.flutter.dev/flutter/material/showDateRangePicker.html
```

Moreover, the plugin is no longer functional with Flutter (beta, master) because it uses `ButtonTheme.bar` which is deprecated and removed (flutter/flutter/pull/73746).

But [showDateRangePicker](https://api.flutter.dev/flutter/material/showDateRangePicker.html) not have the following features: `DatePickerMode`, `SelectableDayPredicate`.

An interim solution would be to use https://github.com/danvick/flutter_form_builder/issues/698#issuecomment-774011017

**Comment by alexmarkley** [comment]
This seems to be a blocker on Flutter 2.0.0 stable.

**Comment by Shiba-Kar** [comment]
For temporary fix ``` .fromButtonThemeData ``` instead of  ``` .bar ```

**Comment by liudonghua123** [comment]
To make it work for flutter 2.0, I need to update `pubspec.yaml` with the following key changes. *No code changes.*

```yaml
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  overlay_support: ^1.2.0-nullsafety.0

dependency_overrides:
  date_range_picker:
    git:
      url: git://github.com/justkawal/date_range_picker.git
      ref: master
  country_pickers:
    git:
      url: git://github.com/justkawal/country_pickers.git
      ref: master
```

@justkawal Thanks for your work.

Some related issue list here: https://github.com/anicdh/date_range_picker/issues/47, https://github.com/figengungor/country_pickers/issues/59
