### ISSUE TITLE
[date_range_picker-1.0.6][flutter_form_builder: ^4.2.0] error GB1B8BC88: Method not found: 'ButtonTheme.bar'.

### ISSUE THREAD

**Issue by Shiba-Kar** [danvick/flutter_form_builder#727]
Getting this Error on Windows build Flutter stable channel 2.0

**Comment by Ojmit** [comment]
Does anyone have a fix for this please?

**Comment by Shiba-Kar** [comment]
```
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  overlay_support: ^1.2.0-nullsafety.0

dependency_overrides:
  date_range_picker:
    git:
      url: git://github.com/justkawal/date_range_picker.git
      ref: master
  country_pickers:
    git:
      url: git://github.com/justkawal/country_pickers.git
      ref: master
```
