### ISSUE TITLE
Cannot build app with flutter_form_builder: ^5.0.0 as dependency

### ISSUE THREAD

**Issue by pankrys** [danvick/flutter_form_builder#772]
Hi! I have some problem with dependency when i build myapp.

```
[sahatyapp] flutter pub get
Running "flutter pub get" in sahatyapp...                       
Because vin_decoder >=0.1.2 <0.1.3 depends on http ^0.12.1 which depends on http_parser >=0.0.1 <4.0.0, vin_decoder >=0.1.2 <0.1.3 requires http_parser >=0.0.1 <4.0.0.

And because validators ^2.0.1 depends on vin_decoder ^0.1.2 and vin_decoder >=0.1.3 <0.2.0-nullsafety depends on http ^0.12.2, validators ^2.0.1 requires http_parser >=0.0.1 <4.0.0 or http ^0.12.2.

Because no versions of http match >0.12.2 <0.13.0 and http 0.12.2 depends on http_parser >=0.0.1 <4.0.0, http ^0.12.2 requires http_parser >=0.0.1 <4.0.0.

Thus, validators ^2.0.1 requires http_parser >=0.0.1 <4.0.0.

And because flutter_form_builder >=4.0.0-alpha.3 <6.0.0-nullsafety.0 depends on validators ^2.0.1, flutter_form_builder >=4.0.0-alpha.3 <6.0.0-nullsafety.0 requires http_parser >=0.0.1 <4.0.0.

And because firebase_auth >=1.0.3 depends on firebase_auth_web ^1.0.5 which depends on http_parser ^4.0.0, flutter_form_builder >=4.0.0-alpha.3 <6.0.0-nullsafety.0 is incompatible with firebase_auth >=1.0.3.

So, because sahatyapp depends on both firebase_auth ^1.0.3 and flutter_form_builder ^5.0.0, version solving failed.
pub get failed (1; So, because sahatyapp depends on both firebase_auth ^1.0.3 and flutter_form_builder ^5.0.0, version solving failed.)

```

My  pubspec.yaml is:

```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^1.0.3"   #"^0.7.0"
  firebase_auth: "^1.0.3"  #0.20.0+1
  firebase_database: "^6.0.0"
  cloud_firestore:  "^1.0.4"     #"^0.16.0+1"
  intl: "^0.17.0"   #0.16.1  
  hive: "^2.0.2"
  hive_flutter: "^1.0.0"


  cupertino_icons: ^1.0.0
  provider: ^4.1.2
  flutter_form_builder: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner: ^1.12.2
```
