### ISSUE TITLE
Publish new release containing recent bug fixes?

### ISSUE THREAD

**Issue by w1th0utnam3** [danvick/flutter_form_builder#943]
First off, thanks for working on these packages, they are super helpful! I don't want to sound rude and know that as an Open Source maintainer you probably have a lot of other issues. Still, would it be possible for you to soon publish a minor releases of `flutter_form_builder` and `form_builder_extra_fields`? I was experimenting with the two packages and while using them stumbled over the recently fixed bugs #926 and #901. As the last release of the two packages is already almost 3 months old I think it would make sense to publish new versions containing these fixes.

As a workaround I currently use git dependency overrides:
```yaml
dependency_overrides:
  flutter_form_builder:
    git: 
      url: https://github.com/danvick/flutter_form_builder
      ref: fa0a26c830c9ae7753bb4ad1d9aa1a126c593322
      path: packages/flutter_form_builder
  form_builder_extra_fields:
    git: 
      url: https://github.com/danvick/flutter_form_builder
      ref: fa0a26c830c9ae7753bb4ad1d9aa1a126c593322
      path: packages/form_builder_extra_fields
  form_builder_validators:
    git: 
      url: https://github.com/danvick/flutter_form_builder
      ref: fa0a26c830c9ae7753bb4ad1d9aa1a126c593322
      path: packages/form_builder_validators
```
