### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by LucaGabi** [danvick/flutter_form_builder#96]
After adding   flutter_form_builder: 3.2.8 as a dep. the app is crashing..

```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: ^2.0.1
  get_it:
  http: ^0.12.0+2
  google_sign_in:
  flutter_form_builder: 3.2.8
```
